-- Create tables 
-- Currencies list
CREATE TABLE dbo.[LKP_CRCD] (
CRCD 	char(3)		NOT NULL PRIMARY KEY,
DESCR	varchar(100) 	NOT NULL) ; 

-- TXNS statuses
CREATE TABLE dbo.[LKP_STATUS] (
STATUS 	varchar(15)		NOT NULL PRIMARY KEY,
DESCR	varchar(100) 	NOT NULL) ; 

-- Input data Types
CREATE TABLE dbo.[LKP_DATA_TYPE] (
DATA_TYPE 	varchar(15)	NOT NULL PRIMARY KEY,
DESCR		varchar(100) 	NOT NULL) ; 

CREATE TABLE dbo.[DECM_INIT] (
ATTR_DOMAIN	varchar(20)  NOT NULL
CONSTRAINT DEF_DOMAIN DEFAULT 'CFG',  
ATTR_NAME	varchar(20) NOT NULL,
ATTR_TYPE	varchar(15) NOT NULL
CONSTRAINT FK_DECM_INIT_DTYPE FOREIGN KEY (ATTR_TYPE)
     REFERENCES dbo.LKP_DATA_TYPE(DATA_TYPE)
	 ON DELETE NO ACTION
	 ON UPDATE NO ACTION, 
ATTR_VALUE	varchar(4000),
CONSTRAINT PK_DECM_INIT PRIMARY KEY CLUSTERED (ATTR_DOMAIN,ATTR_NAME ASC)  );

-- Alerts Priorities 
CREATE TABLE dbo.[LKP_ALERT_PRIO] (
PRIO	char(1)		NOT NULL PRIMARY KEY,
DESCR	varchar(100) 	NOT NULL) ; 

-- Alerts TYPEs
CREATE TABLE dbo.[LKP_ALERT_TYPE] (
TYPE	char(1)		NOT NULL PRIMARY KEY,
DESCR	varchar(100) 	NOT NULL) ; 

-- Lookup Thresholds Types 
CREATE TABLE dbo.[LKP_THR_TYPE] (
TYPE	char(1)		NOT NULL PRIMARY KEY,
DESCR	varchar(100) 	NOT NULL) ; 

-- Systems IDs
CREATE TABLE dbo.[LKP_PPS_ID] (
PPS_ID 	varchar(10)	NOT NULL PRIMARY KEY,
DESCR	varchar(100) 	NOT NULL) ;

CREATE TABLE dbo.[LKP_TRANS_CODE_MAP] (
TRAN_CODE	tinyint	NOT NULL,
TRAN_TYPE	tinyint	NOT NULL,
SYS_CODE	VARCHAR(10)	NOT NULL,
DESCR		VARCHAR(100),	
CONSTRAINT PK_TRANS_CODE_MAP PRIMARY KEY CLUSTERED (TRAN_CODE,TRAN_TYPE ASC) );  

-- Business Object Model tables 
CREATE TABLE dbo.[CUSTOMERS] (
CUST_ID				INT 		NOT NULL IDENTITY(1,1)
CONSTRAINT PK_CUST_ID PRIMARY KEY CLUSTERED (CUST_ID ASC),
CUST_EXTID			varchar(50),
ACCNT_NET			INT 		NOT NULL,
CRCD				CHAR(3)		NOT NULL
CONSTRAINT FK_CUSTOMERS_CRCD FOREIGN KEY (CRCD)
     REFERENCES dbo.LKP_CRCD (CRCD)
	 ON DELETE NO ACTION
	 ON UPDATE NO ACTION, 
CUST_NAME	varchar(120)	NOT NULL,
PARENT_ID			INT NULL
CONSTRAINT FK_CUSTOMERS_PARENT FOREIGN KEY (PARENT_ID)
     REFERENCES dbo.CUSTOMERS (CUST_ID)
	 ON DELETE NO ACTION
	 ON UPDATE NO ACTION, 
IS_SUBSIDIARY			BIT	NOT NULL 
CONSTRAINT DEF_CUSTOMERS_IS_SUBSIDIARY DEFAULT 0,
CHECK_CAPACITY			BIT	NOT NULL 	
CONSTRAINT DEF_CUSTOMERS_CHECK_CAPACITY DEFAULT 0,
MAKE_DECISIONS 			BIT	NOT NULL
CONSTRAINT DEF_CUSTOMERS_MAKE_DECISIONS DEFAULT 0,
SEND_ALERTS 			BIT	NOT NULL
CONSTRAINT DEF_CUSTOMERS_SEND_ALERTS DEFAULT 0,
CHECK_LIMITS 			BIT	NOT NULL
CONSTRAINT DEF_CUSTOMERS_CHECK_LIMITS DEFAULT 0,
IS_HIDDEN 			BIT	NOT NULL
CONSTRAINT DEF_CUSTOMERS_IS_HIDDEN DEFAULT 0,
CUST_TYPE 			TINYINT,	
HEAD_FI_ID			INT NULL
CONSTRAINT FK_CUSTOMERS_HEAD FOREIGN KEY (HEAD_FI_ID)
     REFERENCES dbo.CUSTOMERS (CUST_ID)
	 ON DELETE NO ACTION
	 ON UPDATE NO ACTION, 
LIMIT_SOFT	decimal(18,2)		NOT NULL	
CONSTRAINT DEF_CUSTOMERS_LIMIT_SOFT DEFAULT 0,
LIMIT_HARD	decimal(18,2)		NOT NULL
CONSTRAINT DEF_CUSTOMERS_LIMIT_HARD DEFAULT 0,
ADDR_WARN	varchar(100),
ADDR_ALERT	varchar(100),
ADDR_STOP	varchar(100),
TEMPL_WARN	varchar(50),
TEMPL_ALERT	varchar(50),
TEMPL_OD	varchar(50),
TEMPL_STOP	varchar(50) ) ;

CREATE UNIQUE INDEX IX_NETACCNT_CRCD ON dbo.[CUSTOMERS] (ACCNT_NET, CRCD);

CREATE TABLE dbo.[CUSTOMERS_RULES] (
CUST_ID		int 	NOT NULL 
CONSTRAINT FK_CUST_RULES_ID FOREIGN KEY 
  REFERENCES dbo.[CUSTOMERS] (CUST_ID)
  ON DELETE CASCADE
  ON UPDATE CASCADE,
THR_VALUE	Decimal(18,2)	NOT NULL
CONSTRAINT DEF_CUSTOMERS_RULES_THR_VALUE DEFAULT 0,
THR_VALUE_TYPE	char(1)	NOT NULL
CONSTRAINT DEF_CUST_RULES_VALUE_TYPE DEFAULT 'P'  
CONSTRAINT FK_CUST_RULES_THR_TYPE FOREIGN KEY 
  REFERENCES dbo.[LKP_THR_TYPE] (TYPE)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
THR_PROGR	tinyint 	NOT NULL
CONSTRAINT DEF_CUST_RULES_PROGR DEFAULT 1, 
THR_CUMUL	tinyint 	NOT NULL
CONSTRAINT DEF_CUST_RULES_CUMUL DEFAULT 0, 
THR_TEMPL	varchar(50),
THR_CHANNELS	varchar(50),
ALERT_PRIO	char(1)	NOT NULL
CONSTRAINT DEFAULT_PRIO DEFAULT 'L'  
CONSTRAINT FK_CUST_RULES_PRIO FOREIGN KEY 
  REFERENCES dbo.LKP_ALERT_PRIO (PRIO)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
ALERT_TYPE	char(1)	NOT NULL
CONSTRAINT DEFAULT_TYPE DEFAULT 'W'
CONSTRAINT FK_CUST_RULES_ALERT_TYPE FOREIGN KEY 
  REFERENCES dbo.LKP_ALERT_TYPE (TYPE)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION, 
CONSTRAINT PK_CUST_RULES PRIMARY KEY CLUSTERED (CUST_ID,THR_VALUE_TYPE,THR_VALUE ASC) );  

CREATE TABLE dbo.[ALERTS] (
ALERT_ID	bigint 		NOT NULL IDENTITY(1,1),
DATE_PROC	Date 		NOT NULL,
ALERT_PRIO	char(1)	NOT NULL
CONSTRAINT DEF_PRIO DEFAULT 'L'
CONSTRAINT FK_ALERTS_PRIO FOREIGN KEY 
  REFERENCES dbo.[LKP_ALERT_PRIO] (PRIO)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
ALERT_TYPE	char(1)	NOT NULL
CONSTRAINT DEF_TYPE DEFAULT 'W'
CONSTRAINT FK_ALERTS_TYPE FOREIGN KEY 
  REFERENCES dbo.[LKP_ALERT_TYPE] (TYPE)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,  
CUST_ID		int	NULL
CONSTRAINT FK_ALERTS_CUST_ID FOREIGN KEY 
  REFERENCES dbo.[CUSTOMERS] (CUST_ID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
ACCNT_NET	INT					NULL,
CRCD		char(3)				NULL,
ALERT_ACTIVE	tinyint			NOT NULL
CONSTRAINT DEF_ACTIVE DEFAULT 1, 
CHECK (ALERT_ACTIVE IN (0, 1)), 
THR_VALUE_REL   decimal(18,2)	NOT NULL
CONSTRAINT DEF_ALERTS_THR_VALUE_REL DEFAULT 0,	
THR_VALUE_TYPE	CHAR(1)			NOT NULL,
THR_VALUE_ABS   decimal(18,2)	NOT NULL
CONSTRAINT DEF_ALERTS_THR_VALUE_ABS DEFAULT 0,		
AMOUNT		DECIMAL(18,2)		NOT NULL
CONSTRAINT DEF_ALERTS_AMOUNT DEFAULT 0,
CAPACITY	DECIMAL(18,2)		NOT NULL
CONSTRAINT DEF_ALERTS_CAPACITY DEFAULT 0,
ALERT_PAYLOAD	varchar(1000)	NULL,
ALERT_TEMPL	varchar(50)			NOT NULL,
ALERT_SET_TS	Datetime2		NOT NULL
CONSTRAINT DEF_ALERTS_SET DEFAULT CURRENT_TIMESTAMP,
ALERT_DROPPED	Datetime2,	
ALERT_TEXT	varchar(4000),
CONSTRAINT FK_ALERTS_NETACCNT_CRCD FOREIGN KEY (ACCNT_NET, CRCD)
     REFERENCES dbo.CUSTOMERS (ACCNT_NET,CRCD)
	 ON DELETE NO ACTION
	 ON UPDATE NO ACTION, 
CONSTRAINT PK_ALERTS PRIMARY KEY CLUSTERED (ALERT_ID ASC) ); 

CREATE INDEX IDX_ALERTS_DATE_PROC ON ALERTS (DATE_PROC,CUST_ID);
CREATE INDEX IDX_ALERTS_CUST_ID ON ALERTS (CUST_ID,ALERT_ACTIVE,DATE_PROC);

CREATE TABLE dbo.[ALERTS_QUEUE] (
ALERT_ID	bigint 		NOT NULL
CONSTRAINT FK_ALERTS_QUEUE_ID FOREIGN KEY 
  REFERENCES dbo.[ALERTS] (ALERT_ID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
DATE_PROC	Date 		NOT NULL,
TIME2FIRE	TIME		NOT NULL,
SECONDARY	BIT	
CONSTRAINT DEF_ALERTS_QUEUE_SECONDARY DEFAULT 0,
ALERT_FIRED	Datetime2,
ENTERED_TS  	DATETIME2
CONSTRAINT DEF_ALERTS_QUEUE_ENTERED_TS DEFAULT CURRENT_TIMESTAMP
CONSTRAINT PK_ALERTS_QUEUE PRIMARY KEY CLUSTERED (ALERT_ID,DATE_PROC,TIME2FIRE DESC) ); 

CREATE INDEX IDX_ALERTS_QUEUE_DATE_PROC ON ALERTS_QUEUE(DATE_PROC,ALERT_ID);
	
CREATE TABLE dbo.[LOG_EVENTS] (
LOGGED_ID		bigint		NOT NULL IDENTITY(1,1),
DATE_PROC		Date		NOT NULL,
PLACED_TS		Datetime2	NOT NULL
CONSTRAINT DEF_LOG_EVENTS_PLACED DEFAULT CURRENT_TIMESTAMP,
EVENT_CAT		Varchar(20)	NOT NULL,
EVENT_CODE		Varchar(20)	NOT NULL,
EVENT_SEVERITY  	varchar(10),     	
EVENT_PAYLOAD		Varchar(2000),
EVENT_NOTES		Varchar(2000),
CUST_ID			int,
ACCNT			int,
CRCD			char(3),
AMOUNT			Decimal(18,2),
BALANCE 		DECIMAL(18,2),
ZENOSS_PUBLISHED_TS	Datetime2,
CONSTRAINT PK_LOG_EVENTS PRIMARY KEY CLUSTERED (LOGGED_ID ASC) );

CREATE INDEX IDX_LOG_EVENTS_DATES ON LOG_EVENTS (DATE_PROC) ;

CREATE TABLE dbo.[LOG_CHANGES] (
LOGGED_ID		bigint		NOT NULL IDENTITY(1,1),
DATE_PROC		Date		NOT NULL,
PLACED_TS		Datetime2	NOT NULL
CONSTRAINT DEF_LOG_CHANGES_PLACED DEFAULT CURRENT_TIMESTAMP,
ENTITY_CODE		Varchar(30)	NOT NULL,   	
PAYLOAD			Varchar(2000),
CUST_ID			int,
ACCNT			int,
CRCD			char(3),
CONSTRAINT PK_LOG_CHANGES PRIMARY KEY CLUSTERED (LOGGED_ID ASC) );

CREATE INDEX IDX_LOG_CHANGES_DATES ON LOG_CHANGES (DATE_PROC) ;

CREATE TABLE dbo.[LOG_FILES] (
FILE_NAME	varchar(100)	NOT NULL PRIMARY KEY,
DATE_PROC	Date		NOT NULL,
PLACED_TS	Datetime2	NOT NULL
CONSTRAINT DEF_LOG_FILES_PLACED DEFAULT CURRENT_TIMESTAMP,
RESULT		varchar(50)	NOT NULL,
CNT_ROWS	int,
NOTES       	varchar(200));

CREATE TABLE dbo.[HEARTBEAT] (
PROC_NAME		varchar(20) 	NOT NULL	PRIMARY KEY,
PROC_LATENCY_MAX	smallint	NOT NULL,
PROC_LATEST_TS		Datetime2
   CONSTRAINT DEF_HEARTBEAT_LATEST_TS DEFAULT CURRENT_TIMESTAMP,
PROC_EXC_AT		Datetime2,
PROC_RESTART_AT		Datetime2,
ALERT_FIRED		Datetime2,
ALERT_SENT_TO		varchar(50) );

CREATE TABLE dbo.[TXNS] (
TSEQ		bigint		NOT NULL IDENTITY(1,1),
PPS_ID		varchar(10)	NOT NULL
  CONSTRAINT FK_TXNS_PPS_ID FOREIGN KEY (PPS_ID)
     REFERENCES dbo.LKP_PPS_ID (PPS_ID)
	 ON DELETE NO ACTION
	 ON UPDATE NO ACTION, 
ENTERED_TS	datetime2	NOT NULL
  CONSTRAINT DEF_TXNS_TS DEFAULT CURRENT_TIMESTAMP,
STATUS		varchar(15)	NOT NULL
  CONSTRAINT FK_TXNS_STATUS FOREIGN KEY 
  	REFERENCES dbo.[LKP_STATUS] (STATUS)
  	ON DELETE NO ACTION
  	ON UPDATE NO ACTION,
AMOUNT_DR	decimal(18,2),
ACCNT_DR	varchar(25),
CRCD_DR		char(3) NULL
  CONSTRAINT FK_TXNS_CRCD_DR FOREIGN KEY (CRCD_DR)
     REFERENCES dbo.LKP_CRCD (CRCD)
	 ON DELETE NO ACTION
	 ON UPDATE NO ACTION, 
AMOUNT_CR	decimal(18,2),	
ACCNT_CR	varchar(25),
CRCD_CR		char(3) NULL
  CONSTRAINT FK_TXNS_CRCD_CR FOREIGN KEY (CRCD_CR)
     REFERENCES dbo.LKP_CRCD (CRCD)
	 ON DELETE NO ACTION
	 ON UPDATE NO ACTION, 
DATE_PROC	date		NOT NULL,		
DATE_EFD	date,
GUID		varchar(50),
CODE		varchar(10),
TYPE		varchar(10),
MESSAGE		varchar(max),
PROCESSED_TS	datetime2,
CONSTRAINT PK_TXNS PRIMARY KEY CLUSTERED (TSEQ ASC) );

CREATE INDEX [IX_TXNS_PROCESSED_TS_STATUS] ON [TXNS] ([PROCESSED_TS],[STATUS])

CREATE TABLE dbo.[TOTALS_NET] (
DATE_PROC		date		NOT NULL,
CUST_ID			int		NOT NULL
CONSTRAINT FK_TOTALS_NET_CUST_ID FOREIGN KEY 
  REFERENCES dbo.[CUSTOMERS] (CUST_ID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
ACCNT_NET		int		NOT NULL,
CRCD			char(3)	NOT NULL,	
REC_TYPE		varchar(20),
LINE_OF_CR		Decimal(18,2)	NOT NULL
CONSTRAINT DEF_TOTALS_NET_LOC DEFAULT 0,
OTHER_CR_AVAIL		Decimal(18,2)	NOT NULL
CONSTRAINT DEF_TOTALS_NET_OTHER_CR DEFAULT 0,
BAL_CURR		Decimal(18,2)	NOT NULL
CONSTRAINT DEF_TOTALS_NET_BAL DEFAULT 0,
CAPACITY		Decimal(18,2)	NOT NULL
CONSTRAINT DEF_TOTALS_NET_CAPACITY DEFAULT 0,
PAYLOAD			VARCHAR(400),
CONSTRAINT FK_TOTALS_NET_NETACCNT_CRCD FOREIGN KEY (ACCNT_NET, CRCD)
     REFERENCES dbo.CUSTOMERS (ACCNT_NET,CRCD)
	 ON DELETE NO ACTION
	 ON UPDATE NO ACTION, 
CONSTRAINT PK_TOTALS_NET PRIMARY KEY CLUSTERED (DATE_PROC,CUST_ID,ACCNT_NET,CRCD ASC) );

CREATE INDEX [IX_TOTALS_NET_CUST_ID] ON [TOTALS_NET](CUST_ID) INCLUDE(DATE_PROC, ACCNT_NET,CRCD,BAL_CURR, LINE_OF_CR, CAPACITY);


CREATE TABLE dbo.[TOTALS] (
DATE_PROC		date	NOT NULL,
CUST_ID			int	NOT NULL
CONSTRAINT FK_TOTALS_CUST_ID FOREIGN KEY 
  REFERENCES dbo.[CUSTOMERS] (CUST_ID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
ACCNT_NET		int		NOT NULL,
CRCD			char(3)		NOT NULL,
PPS_ID			varchar(10)	NOT NULL
  CONSTRAINT FK_TOTALS_PPS_ID FOREIGN KEY (PPS_ID)
     REFERENCES dbo.LKP_PPS_ID (PPS_ID)
	 ON DELETE NO ACTION
	 ON UPDATE NO ACTION, 
REC_TYPE		varchar(20),
AMT_CDT_DR_SET		Decimal(18,2)	NOT NULL
CONSTRAINT DEF_TOTALS_DR_SET_AMT DEFAULT 0,
AMT_CDT_CR_SET		Decimal(18,2)	NOT NULL
CONSTRAINT DEF_TOTALS_CR_SET_AMT DEFAULT 0,
AMT_CDT_DR_UNSET	Decimal(18,2)	NOT NULL
CONSTRAINT DEF_TOTALS_DR_UNSET_AMT DEFAULT 0,
AMT_CDT_CR_UNSET	Decimal(18,2)	NOT NULL
CONSTRAINT DEF_TOTALS_CR_UNSET_AMT DEFAULT 0,
AMT_CDT_DR_STOP		Decimal(18,2)	NOT NULL
CONSTRAINT DEF_TOTALS_DR_STOP_AMT DEFAULT 0,
AMT_CDT_CR_STOP		Decimal(18,2)	NOT NULL
CONSTRAINT DEF_TOTALS_CR_STOP_AMT DEFAULT 0,
AMT_CDT_DR_REJ		Decimal(18,2)	NOT NULL
CONSTRAINT DEF_TOTALS_DR_REJ_AMT DEFAULT 0,
AMT_CDT_CR_REJ		Decimal(18,2)	NOT NULL
CONSTRAINT DEF_TOTALS_CR_REJ_AMT DEFAULT 0,
AMT_EFD_DR		Decimal(18,2)	NOT NULL
CONSTRAINT DEF_TOTALS_DR_EFD_AMT DEFAULT 0,
AMT_EFD_CR		Decimal(18,2)	NOT NULL
CONSTRAINT DEF_TOTALS_CR_EFD_AMT DEFAULT 0,
CNT_CDT_DR_SET		int	NOT NULL
CONSTRAINT DEF_TOTALS_DR_SET_CNT DEFAULT 0,
CNT_CDT_CR_SET		int	NOT NULL
CONSTRAINT DEF_TOTALS_CR_SET_CNT DEFAULT 0,
CNT_CDT_DR_UNSET	int	NOT NULL
CONSTRAINT DEF_TOTALS_DR_UNSET_CNT DEFAULT 0,
CNT_CDT_CR_UNSET	int	NOT NULL
CONSTRAINT DEF_TOTALS_CR_UNSET_CNT DEFAULT 0,
CNT_CDT_DR_STOP		int	NOT NULL
CONSTRAINT DEF_TOTALS_DR_STOP_CNT DEFAULT 0,
CNT_CDT_CR_STOP		int	NOT NULL
CONSTRAINT DEF_TOTALS_CR_STOP_CNT DEFAULT 0,
CNT_CDT_DR_REJ		int	NOT NULL
CONSTRAINT DEF_TOTALS_DR_REJ_CNT DEFAULT 0,
CNT_CDT_CR_REJ		int	NOT NULL
CONSTRAINT DEF_TOTALS_CR_REJ_CNT DEFAULT 0,
CNT_EFD_DR		int	NOT NULL
CONSTRAINT DEF_TOTALS_DR_EFD_CNT DEFAULT 0,
CNT_EFD_CR		int	NOT NULL
CONSTRAINT DEF_TOTALS_CR_EFD_CNT DEFAULT 0,
PAYLOAD			VARCHAR(400),
CONSTRAINT FK_TOTALS_NETACCNT_CRCD FOREIGN KEY (ACCNT_NET, CRCD)
     REFERENCES dbo.CUSTOMERS (ACCNT_NET,CRCD)
	 ON DELETE NO ACTION
	 ON UPDATE NO ACTION, 
CONSTRAINT PK_TOTALS PRIMARY KEY CLUSTERED (DATE_PROC, CUST_ID,ACCNT_NET,CRCD,PPS_ID ASC) );

CREATE INDEX [IX_TOTALS_CUST_ID] ON [TOTALS](CUST_ID) INCLUDE(DATE_PROC, ACCNT_NET,CRCD,PPS_ID);


CREATE TABLE dbo.[TXNS_INDEX] (
DATE_PROC		date		NOT NULL,
STATUS 			varchar(15)	NOT NULL
CONSTRAINT FK_TXNS_IDX_STATUS FOREIGN KEY (STATUS)
     REFERENCES dbo.LKP_STATUS (STATUS)
	 ON DELETE NO ACTION
	 ON UPDATE NO ACTION, 
CUST_ID			int		NOT NULL
CONSTRAINT FK_TXN_INDEX_CUST_ID FOREIGN KEY 
  REFERENCES dbo.[CUSTOMERS] (CUST_ID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
PPS_ID			varchar(10)	NOT NULL
  CONSTRAINT FK_TXNS_INDEX_PPS_ID FOREIGN KEY (PPS_ID)
     REFERENCES dbo.LKP_PPS_ID (PPS_ID)
	 ON DELETE NO ACTION
	 ON UPDATE NO ACTION, 
ACCNT_NET		int		NOT NULL,
CRCD			char(3)		NOT NULL,
TSEQ			bigint		NOT NULL,
GUID			varchar(50),
TSEQ_ORIG		bigint,
AMOUNT			decimal(18,2),
DESCRIPTION     	varchar(120),
DATE_EFD		Date,
CONSTRAINT FK_TXN_INDEX_NETACCNT_CRCD FOREIGN KEY (ACCNT_NET, CRCD)
     REFERENCES dbo.CUSTOMERS (ACCNT_NET,CRCD)
	 ON DELETE NO ACTION
	 ON UPDATE NO ACTION, 
CONSTRAINT PK_TXNS_INDEX PRIMARY KEY CLUSTERED (DATE_PROC, STATUS, CUST_ID, PPS_ID,ACCNT_NET,CRCD,TSEQ ASC) );

CREATE TABLE dbo.[TXNS_TRACE] (
DATE_PROC	Date	NOT NULL 	PRIMARY KEY,
TSEQ_START	bigint,	
TSEQ_END	bigint)

CREATE TABLE dbo.[NBD_CALENDAR] (
NBD_CODE	varchar(12)	NOT NULL
CONSTRAINT DEF_NBD_CALENDAT_CODE DEFAULT 'CAN-FED', 
NBD_DATE	Date		NOT NULL,
NBD_FLAG 	TINYINT NOT NULL 
	CONSTRAINT DEF_NBD_FLAG DEFAULT 0, 
NBD_DESCR	Varchar(50),
CONSTRAINT PK_NBD_CALENDAR PRIMARY KEY CLUSTERED (NBD_CODE,NBD_DATE ASC) );

CREATE TABLE dbo.[ACCOUNTS] (
ACCNT_TRANSIT	INT		NOT NULL,
CRCD		CHAR(3)		NOT NULL,
ACCNT_NET	INT		NOT NULL,
 CONSTRAINT FK_NETACCNT_CRCD FOREIGN KEY (ACCNT_NET, CRCD)
     REFERENCES dbo.[CUSTOMERS] (ACCNT_NET,CRCD)
	 ON DELETE NO ACTION
	 ON UPDATE NO ACTION, 
STATUS		TINYINT		NOT NULL,
CUST_ID		INT NOT NULL,
CUST_NAME	VARCHAR(100),
ACCNT_NAME	VARCHAR(100),
CONSTRAINT PK_ACCOUNTS_TRANSIT_CRCD PRIMARY KEY CLUSTERED (ACCNT_TRANSIT,CRCD ASC) );

CREATE INDEX IDX_ACCOUNTS_CUST_ID ON ACCOUNTS (CUST_ID ASC) INCLUDE (ACCNT_TRANSIT, ACCNT_NET,CRCD);
CREATE INDEX IDX_ACCOUNTS_ACCNT_NET ON ACCOUNTS (ACCNT_NET,CRCD ASC) INCLUDE (ACCNT_TRANSIT,CUST_ID);

-- Spring Batch tables - autogenerated

CREATE TABLE BATCH_JOB_INSTANCE  (
	JOB_INSTANCE_ID BIGINT  NOT NULL PRIMARY KEY ,
	VERSION BIGINT NULL,
	JOB_NAME VARCHAR(100) NOT NULL,
	JOB_KEY VARCHAR(32) NOT NULL,
	constraint JOB_INST_UN unique (JOB_NAME, JOB_KEY)
) ;

CREATE TABLE BATCH_JOB_EXECUTION  (
	JOB_EXECUTION_ID BIGINT  NOT NULL PRIMARY KEY ,
	VERSION BIGINT NULL,
	JOB_INSTANCE_ID BIGINT NOT NULL,
	CREATE_TIME DATETIME NOT NULL,
	START_TIME DATETIME DEFAULT NULL ,
	END_TIME DATETIME DEFAULT NULL ,
	STATUS VARCHAR(10) NULL,
	EXIT_CODE VARCHAR(2500) NULL,
	EXIT_MESSAGE VARCHAR(2500) NULL,
	LAST_UPDATED DATETIME NULL,
	JOB_CONFIGURATION_LOCATION VARCHAR(2500) NULL,
	constraint JOB_INST_EXEC_FK foreign key (JOB_INSTANCE_ID)
	references BATCH_JOB_INSTANCE(JOB_INSTANCE_ID)
) ;

CREATE TABLE BATCH_JOB_EXECUTION_PARAMS  (
	JOB_EXECUTION_ID BIGINT NOT NULL ,
	TYPE_CD VARCHAR(6) NOT NULL ,
	KEY_NAME VARCHAR(100) NOT NULL ,
	STRING_VAL VARCHAR(250) NULL,
	DATE_VAL DATETIME DEFAULT NULL ,
	LONG_VAL BIGINT NULL,
	DOUBLE_VAL DOUBLE PRECISION NULL,
	IDENTIFYING CHAR(1) NOT NULL ,
	constraint JOB_EXEC_PARAMS_FK foreign key (JOB_EXECUTION_ID)
	references BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
) ;

CREATE TABLE BATCH_STEP_EXECUTION  (
	STEP_EXECUTION_ID BIGINT  NOT NULL PRIMARY KEY ,
	VERSION BIGINT NOT NULL,
	STEP_NAME VARCHAR(100) NOT NULL,
	JOB_EXECUTION_ID BIGINT NOT NULL,
	START_TIME DATETIME NOT NULL ,
	END_TIME DATETIME DEFAULT NULL ,
	STATUS VARCHAR(10) NULL,
	COMMIT_COUNT BIGINT NULL,
	READ_COUNT BIGINT NULL,
	FILTER_COUNT BIGINT NULL,
	WRITE_COUNT BIGINT NULL,
	READ_SKIP_COUNT BIGINT NULL,
	WRITE_SKIP_COUNT BIGINT NULL,
	PROCESS_SKIP_COUNT BIGINT NULL,
	ROLLBACK_COUNT BIGINT NULL,
	EXIT_CODE VARCHAR(2500) NULL,
	EXIT_MESSAGE VARCHAR(2500) NULL,
	LAST_UPDATED DATETIME NULL,
	constraint JOB_EXEC_STEP_FK foreign key (JOB_EXECUTION_ID)
	references BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
) ;

CREATE TABLE BATCH_STEP_EXECUTION_CONTEXT  (
	STEP_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
	SHORT_CONTEXT VARCHAR(2500) NOT NULL,
	SERIALIZED_CONTEXT TEXT NULL,
	constraint STEP_EXEC_CTX_FK foreign key (STEP_EXECUTION_ID)
	references BATCH_STEP_EXECUTION(STEP_EXECUTION_ID)
) ;

CREATE TABLE BATCH_JOB_EXECUTION_CONTEXT  (
	JOB_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
	SHORT_CONTEXT VARCHAR(2500) NOT NULL,
	SERIALIZED_CONTEXT TEXT NULL,
	constraint JOB_EXEC_CTX_FK foreign key (JOB_EXECUTION_ID)
	references BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
) ;

CREATE TABLE BATCH_STEP_EXECUTION_SEQ (ID BIGINT IDENTITY);
CREATE TABLE BATCH_JOB_EXECUTION_SEQ (ID BIGINT IDENTITY);
CREATE TABLE BATCH_JOB_SEQ (ID BIGINT IDENTITY);





